import{a as b,S as w,i as a}from"./assets/vendor-BgmC94F3.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const S="https://pixabay.com/api/",v="53020322-8236fb03113a5119ee0fdb502";async function u(s,r=1){try{const e={key:v,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r};return(await b.get(S,{params:e})).data}catch(e){throw console.error("❌ Error fetching images:",e),e}}const h=document.querySelector(".gallery"),f=document.querySelector(".loader"),m=document.querySelector(".load-more");let q=new w(".gallery a",{captionsData:"alt",captionDelay:250});function p(s){const r=s.map(e=>`
        <li class="gallery-item">
          <a href="${e.largeImageURL}">
            <img src="${e.webformatURL}" alt="${e.tags}" />
          </a>
          <div class="info">
            <p><b>Likes:</b> ${e.likes}</p>
            <p><b>Views:</b> ${e.views}</p>
            <p><b>Comments:</b> ${e.comments}</p>
            <p><b>Downloads:</b> ${e.downloads}</p>
          </div>
        </li>
      `).join("");h.insertAdjacentHTML("beforeend",r),q.refresh()}function E(){h.innerHTML=""}function g(){f.classList.remove("is-hidden")}function i(){f.classList.add("is-hidden")}function P(){m.classList.remove("is-hidden")}function y(){m.classList.add("is-hidden")}const R=document.querySelector(".form"),B=document.querySelector(".load-more");let n=1,d="",L=0;R.addEventListener("submit",async s=>{s.preventDefault();const r=s.target.elements["search-text"].value.trim();if(!r){a.warning({title:"Warning",message:"Please enter a search term.",position:"topRight"});return}d=r,n=1,E(),y(),g();try{const e=await u(d,n);if(i(),L=e.totalHits,e.hits.length===0){a.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p(e.hits),P()}catch(e){i(),a.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(e)}});B.addEventListener("click",async()=>{n+=1,g();try{const s=await u(d,n);i(),p(s.hits);const r=document.querySelector(".gallery").firstElementChild.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"}),n*15>=L&&(y(),a.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{i(),a.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}});
//# sourceMappingURL=index.js.map
